## https://github.com/leolee3914/real_lift
name: real_lift
main: real_lift\Main
version: 2.0.1
api: [4.0.0]
## https://github.com/leolee3914/real_lift
load: POSTWORLD
author: Leolee3914
description: real_lift